"""empty message

Revision ID: 04ea7c9d4b63
Revises: 28bbd388646c
Create Date: 2024-05-23 13:49:42.870851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ea7c9d4b63'
down_revision = '28bbd388646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_teacher_account'), ['account'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teacher_account'), type_='unique')

    # ### end Alembic commands ###
