"""empty message

Revision ID: 537205feec95
Revises: a80cf461b649
Create Date: 2024-05-23 00:24:31.677404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537205feec95'
down_revision = 'a80cf461b649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type', sa.String(length=10), nullable=False))
        batch_op.drop_column('_type')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Class', sa.Integer(), nullable=False))
        batch_op.drop_column('_class')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=34),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=34),
               existing_nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_class', sa.INTEGER(), nullable=False))
        batch_op.drop_column('Class')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_type', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('Type')

    # ### end Alembic commands ###
