"""empty message

Revision ID: 5b8f629669a4
Revises: 
Create Date: 2024-05-26 22:52:26.700842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8f629669a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('Class', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('grade', 'Class', 'number', name=op.f('uq_student_grade'))
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=62), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher')),
    sa.UniqueConstraint('account', name=op.f('uq_teacher_account'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_type', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_event_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_event_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('score_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_point', sa.Integer(), nullable=True),
    sa.Column('n_point', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['student.id'], name=op.f('fk_score_board_id_student'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_board'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_board')
    op.drop_table('event')
    op.drop_table('teacher')
    op.drop_table('student')
    # ### end Alembic commands ###
