"""empty message

Revision ID: a80cf461b649
Revises: cecdd7a2cf34
Create Date: 2024-05-22 14:13:13.683900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80cf461b649'
down_revision = 'cecdd7a2cf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=34), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
