"""empty message

Revision ID: cecdd7a2cf34
Revises: 3dfc3df133d4
Create Date: 2024-05-22 13:57:54.499361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecdd7a2cf34'
down_revision = '3dfc3df133d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('_class', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('point')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('number')
        batch_op.drop_column('_class')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
